### ISSUE TITLE
No secret s on proving algorithm

### ISSUE THREAD

**Issue by antoniofaonio** [HuyHung0/cqplus#2]
https://github.com/HuyHung0/cqplus/blob/267047985be0ff4dc87651a63ee5e586458890c2/src/prover.rs#L47

The prover cannot take $s$ as input.

**Comment by HuyHung0** [comment]
Yes, you are correct. I will modify the code soon.

**Comment by HuyHung0** [comment]
The commit 0d04ba6efc238c247f17649eafea28374fc8357b should solved this issue.
